# Generated by Django 3.2.6 on 2021-08-20 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Statement', models.CharField(max_length=1000)),
                ('Name', models.CharField(max_length=25)),
                ('Code', models.CharField(max_length=1000)),
                ('Difficulty', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Testcases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Input', models.CharField(max_length=1000)),
                ('Output', models.CharField(max_length=1000)),
                ('Problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.problems')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(max_length=1000)),
                ('SubmittedAt', models.DateTimeField(verbose_name='submitted at')),
                ('Problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.problems')),
            ],
        ),
    ]
