# Generated by Django 3.2.6 on 2021-08-21 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problems',
            old_name='Code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='problems',
            old_name='Difficulty',
            new_name='difficulty',
        ),
        migrations.RenameField(
            model_name='problems',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='problems',
            old_name='Statement',
            new_name='statement',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='Problem',
            new_name='problem',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='SubmittedAt',
            new_name='submittedAt',
        ),
        migrations.RenameField(
            model_name='testcases',
            old_name='Input',
            new_name='input',
        ),
        migrations.RenameField(
            model_name='testcases',
            old_name='Output',
            new_name='output',
        ),
        migrations.RenameField(
            model_name='testcases',
            old_name='Problem',
            new_name='problem',
        ),
    ]
